Create functionality to search for doctors
dimas1976/Mentalika pull request #29
Opened 2021-09-13 17:41 UTC by dimas1976

fixes #24 

# for reproduction
- put in the search bar for example Berlin or Almond

2021-09-14 13:04 UTC, marwinburesch reviewed
Excellent!
I like the additions, but I would've expected the changes to `DoctorCard` in a different PR.

2021-09-14 13:04 UTC, marwinburesch commented on src/app/pages/Home/Home.tsx
> +    const item = localStorage.getItem('doctors');
But you added the `useLocalStorage` hook, why aren't you using it, I recommend another custom hook. Maybe [this helps](https://github.com/marwinburesch/moviescout/pull/60/files#diff-502316410eec5924d65a1f4c9a9356cc7aeac5c221197ed7e3bc75a0f083a441)

2021-09-14 13:04 UTC, marwinburesch commented on src/app/pages/Home/Home.tsx
> +  const [doctors, setDoctors] = useState<Doctor[]>([]);
This is how `useLocalStorage` would work
```suggestion
  const [doctors, setDoctors] = useLocalStorage<Doctor[]>(mockedDoctors);
```
However, then you would need to use a different state for rendering and filtering your doctors. In that case you won't need another custom hook

2021-09-14 13:04 UTC, marwinburesch commented on src/app/pages/Home/Home.tsx
> +        searchValue === element.surename || searchValue === element.city
These are a bit strict, why don't you look into [`.includes()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/includes) or if you want to be fancy use [Regular Expressions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Cheatsheet).
In any way, I would compare lowercase strings. Another neat thing would be if you would add address, name, surname and city together as strings and then look for your substring

2021-09-15 13:31 UTC, dimas1976 commented on src/app/pages/Home/Home.tsx
> +        searchValue === element.surename || searchValue === element.city
i used regular expressions. Thank you for advice

2021-09-15 13:35 UTC, dimas1976 commented on src/app/pages/Home/Home.tsx
> +    const item = localStorage.getItem('doctors');
I will consider useLOcalStorage later :)

2021-09-15 14:06 UTC, phlgr requested changes

2021-09-15 14:06 UTC, phlgr commented on src/app/components/Searchbar/Searchbar.tsx
> +  onSubmit: (event: React.FormEvent) => void;
```suggestion
  onSubmit: () => void;
```

2021-09-15 14:06 UTC, phlgr commented on src/app/components/Searchbar/Searchbar.tsx
>    return (
```suggestion
}: SearchbarProps): JSX.Element {
  function handleSubmit(event: React.FormEvent) {
    event.preventDefault();
    onSubmit()
  }
  return (
```

2021-09-15 14:06 UTC, phlgr commented on src/app/components/Searchbar/Searchbar.tsx
> +    <form className={`${className} ${styles.form}`} onSubmit={onSubmit}>
```suggestion
    <form className={`${className} ${styles.form}`} onSubmit={handleSubmit}>
```

2021-09-15 16:15 UTC, merged