Create functionality to book an appointment
dimas1976/Mentalika pull request #37
Opened 2021-09-21 15:41 UTC by dimas1976

fixes #36 

- in order to test, search please for the same doctor after booking process. He shouldn' have the booked appointment anymore

# Mockdata
doctors: [{"id":1,"image":"sabine.jpg","title":"Dipl.-Psych.","name":"Sabine","surename":"Wery von Limont","bio":"Hallo, mein Name ist Wery von Limont. Ich bin Diplom-Psychologin, Systemische Therapeutin und Heilpraktikerin für Psychotherapie. In meiner Privatpraxis arbeite ich mit klinischer Hypnose und lösungsorientierten Techniken","adress": "Max-Brauer-Alee 52","plz": 22765,"city": "Hamburg"},{"id":2,"image":"marc.jpg","title":"Dipl.-Psych.","name": "Marc","surename":"Almond","bio":"Gerne unterstütze ich Sie dabei, den passenden Ansatz für Ihr persönliches Anliegen zu finden. Dabei orientiere ich mich an den neuesten wissenschaftlichen Erkenntnissen der Psychotherapieforschung. Ich arbeite beziehungsorientiert und emotionsfokussiert und integriere die modernen und bewährten Verfahrensweisen der dritten Welle der Verhaltenstherapie, wie beispielsweise achtsamkeitsbasierte Ansätze.","adress": "Kastanienalee 18","plz": 10715,"city": "Berlin"}]

appointments: [{"doctorId":1,"availability":[{"date":"2021-10-22T12:00:00","isBooked":false},{"date":"2021-10-23T12:00:00","isBooked":false},{"date":"2021-10-24T09:45:00","isBooked":false}]},{"doctorId":2,"availability":[{"date":"2021-11-02T16:10:00","isBooked":false},{"date":"2021-12-13T15:40:00","isBooked":false},{"date":"2021-12-19T09:45:00","isBooked":false}]}]

2021-09-22 08:38 UTC, phlgr requested changes

2021-09-22 08:38 UTC, phlgr commented on src/app/pages/DoctorProfile/DoctorProfile.tsx
> +
I would suggest creating a custom hook based in useLocalStorage for that

2021-09-23 09:07 UTC, marwinburesch reviewed
Some error messages need more info or reconsideration

2021-09-23 09:07 UTC, marwinburesch commented on src/app/components/AppointmentItem/AppointmentItem.stories.tsx
> +    clickHandle={() => console.log()}
`handleClick` is more conventional, also you should get a TS error here because this arrow function is not accepting any arguments. `AppointmentItemProps` specifies a function that accepts an argument, however. In order to prevent committing TS errors I recommend adding `tsc` (typescript compile) to your `test` script, [like so](https://github.com/marwinburesch/moviescout/blob/6dbae1cc80f17ea1ac28af0d9288ccf4b65026f6/package.json#L13).

2021-09-23 09:07 UTC, marwinburesch commented on src/app/hooks/useAvailableAppointments.ts
> +  return freeDates;
mmmh dates, AND free even! :D

2021-09-23 09:07 UTC, marwinburesch commented on src/app/hooks/useAvailableAppointments.ts
> +    throw new Error('There is no doctor with the ID');
```suggestion
    throw new Error('There is no doctor with this ID');
```

2021-09-23 09:07 UTC, marwinburesch commented on src/app/hooks/useDoctorById.ts
> +      throw new Error('');
You could use this line again
```
throw new Error('There is no doctor with this ID');
```

2021-09-23 09:26 UTC, dimas1976 commented on src/app/hooks/useAvailableAppointments.ts
> +    throw new Error('There is no doctor with the ID');
Thanks :)

2021-09-23 13:39 UTC, marwinburesch reviewed
Nice

2021-09-23 13:39 UTC, marwinburesch commented on src/app/pages/DoctorProfile/DoctorProfile.tsx
> +      console.log('not found');
this should go :)

2021-09-23 13:39 UTC, marwinburesch commented on src/app/lib/types.ts
> +// };
this here is redundant too

2021-09-23 14:24 UTC, merged